"""Data models for the research pipeline."""

from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any
from datetime import datetime
from enum import Enum


class Intent(Enum):
    """Intent categories for user queries."""
    INFORMATIONAL = "informational"
    COMPARATIVE = "comparative"
    NEWS = "news"
    CODE = "code"
    TUTORIAL = "tutorial"
    RESEARCH = "research"
    GENERAL = "general"


@dataclass
class Query:
    """User query with metadata."""
    text: str
    intent: Optional[Intent] = None
    timestamp: datetime = field(default_factory=datetime.now)


@dataclass
class SearchQuery:
    """Individual search query generated by planner."""
    query: str
    purpose: str
    priority: int = 1


@dataclass
class ResearchPlan:
    """Research plan generated by the planner."""
    query: Query
    sections: List[str]
    search_queries: List[SearchQuery]
    rationale: str


@dataclass
class SearchResult:
    """Individual search result."""
    url: str
    title: str
    snippet: str
    rank: int
    relevance_score: Optional[float] = None


@dataclass
class ScrapedContent:
    """Scraped and processed content from a URL."""
    url: str
    title: str
    content: str
    chunks: List[str]
    metadata: Dict[str, str]
    retrieved_at: datetime = field(default_factory=datetime.now)


@dataclass
class Citation:
    """Citation with source information."""
    text: str
    url: str
    title: str
    chunk_id: Optional[int] = None


@dataclass
class Summary:
    """Content summary with citations."""
    text: str
    citations: List[Citation]
    url: str
    relevance_score: float


@dataclass
class ContextPackage:
    """Assembled context for report generation."""
    query: Query
    plan: ResearchPlan
    summaries: List[Summary]
    additional_context: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ReflectionResult:
    """Result of reflection stage."""
    is_complete: bool
    missing_information: List[str]
    additional_queries: List[SearchQuery]
    rationale: str


@dataclass
class Report:
    """Final generated report."""
    query: Query
    content: str
    citations: List[Citation]
    metadata: Dict[str, Any]
    generated_at: datetime = field(default_factory=datetime.now)


@dataclass
class ExtractedClaim:
    """A factual claim extracted from a report."""
    text: str                    # The claim text
    source_number: int          # Which [Source N] cited
    source_url: str             # Actual URL for that source
    claim_type: str             # factual|statistic|quote|date
    context: str = ""           # Surrounding text for context
    additional_sources: Optional[List[str]] = None  # Additional source URLs for multi-source claims


@dataclass
class VerificationResult:
    """Result of verifying a single claim."""
    claim: ExtractedClaim
    verdict: str                # supported|partial|unsupported|contradicted
    confidence: float           # 0.0 to 1.0
    evidence: Optional[str]     # Supporting quote from source
    reasoning: str              # Brief explanation
    source_tier: Optional[str] = None       # tier_1|tier_2|tier_3|tier_4
    adjusted_confidence: Optional[float] = None  # Confidence after source tier weighting


@dataclass
class VerificationSummary:
    """Summary of all verification results for a report."""
    total_claims: int
    supported_claims: int
    partial_claims: int
    unsupported_claims: int
    contradicted_claims: int
    flagged_claims: List[VerificationResult]
    avg_confidence: float
    by_source: Dict[str, List[VerificationResult]] = field(default_factory=dict)
    low_tier_only_claims: List[VerificationResult] = field(default_factory=list)
    tier_distribution: Dict[str, int] = field(default_factory=dict)
